title: <p align="center"> Nick Gasser </p>

logo: "/images/Gasser_Nick.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nicholasgasser/">LinkedIn</a> |
  <a href="https://github.com/nickgasser">GitHub</a>
  </p>
  
  <p align="justify">
  
  <br><br>
  I have over four years of industry experience working in process engineering, management, and data analysis.  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
